<?xml version="1.0"?>
<package format="3">
  <name>fanuc_crx_xy_demo</name>
  <version>0.1.0</version>
  <description>ROS 2 demo package for Raspberry Pi 5 dual AS5600 encoder feedback to FANUC CRX target pose generation.</description>
  <maintainer email="brian.spence@example.com">Brian Spence</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
